[workspace]
members = ["craftgate", "examples/*"]
default-members = ["craftgate"]
resolver = "2"

[workspace.package]
authors = ["Tunahan Karlibas <dvt.tnhn.krlbs@icloud.com>"]
license = "MIT"
publish = false
repository = "https://github.com/dvtkrlbs/craftgate-rs"
edition = "2021"
